generator auto_router by call function instead of cli #5
node-honeycomb/honeycomb-cli pull request #6
Opened 2018-01-28 00:44 UTC by baqian

2018-01-30 02:44 UTC, HQidea requested changes
honeycomb package时也会用到genAutoRouter

2018-01-30 02:44 UTC, HQidea commented on lib/gen_auto_router.js
> +    if(options.compileCallback){
if () {}
括号前后需要有空格

2018-01-30 02:44 UTC, HQidea commented on lib/start.js
> +  genAutoRouter({
放在app = require(appPath);可能会导致app里面拿不到router

2018-02-04 12:30 UTC, baqian commented on lib/start.js
> +  genAutoRouter({
目前代码中只有在app.run时才去获取 auto_router和router，现在有场景在项目的app.js中获取auto_router对象吗

2019-06-13 01:27 UTC, cctv1005s commented
closed，没人维护了

2019-06-13 01:27 UTC, closed without merging